FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-stretch AS build
WORKDIR /src
COPY ["../TestApi.E/TestApi.E.csproj", "../TestApi.E/"]
RUN dotnet restore "../TestApi.E/TestApi.E.csproj"
COPY . .
WORKDIR "/src/../TestApi.E"
RUN dotnet build "TestApi.E.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TestApi.E.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestApi.E.dll"]